spring.application.name=dailymotionminer
server.port=${PORT:8082}

# Dejamos solo la IP y el puerto.
# Tu código en Java ya se encarga de poner el resto (/videominer/channels)
VIDEOMINER_URL=http://localhost:8080

dailymotion.baseuri=https://api.dailymotion.com
dailymotionminer.maxVideos=10
dailymotionminer.maxComments=10